### PR TITLE
update tchannel-go to v1.0.2

### PR DESCRIPTION
**Pull request by CorgiMan**
tickcluster-testing looks good
Need to deploy on test cluster

### CODE REVIEW

**Comment by Motiejus** [comment]
lgtm

**Comment by severb** [comment]
I got a full sync loop in tickcluster on this branch.

**Comment by severb** [comment]
Can't reproduce it neither on this branch on on master anymore. I do see an increased number of full syncs, but I think that's expected because the maxP fix is not included in the branch nor in master.

**Comment by severb** [comment]
Let's Get The Money!

**Pull request merged**
