### PR TITLE
Update TChannel to 1.0.3

### PR DESCRIPTION
**Pull request by dansimau**
* Updated TChannel, ran tests and they passed
* Sanity-checked local deployment, all good

@uber/ringpop

### CODE REVIEW

**Comment by dansimau** [comment]
Looks like the merge has failing tests. Will have to investigate.

**Comment by dansimau** [comment]
Test has passed now. Looks like a flapper

**Comment by dansimau** [comment]
Filed flappy test: https://github.com/uber/ringpop-go/issues/105

**Comment by thanodnl** [comment]
LGTM

**Comment by CorgiMan** [comment]
Looks good

**Pull request merged**
