### PR TITLE
change /admin/member/(leave|join) to /admin/(leave|join) to be compat…

### PR DESCRIPTION
**Pull request by thanodnl**
…ible with ringpop-admin.

### CODE REVIEW

**Comment by thanodnl** [comment]
Maybe worth back porting to the latest release and create a patch release

**Comment by thanodnl** [comment]
and the prove:

```bash
$ ./partitions.js --ring 172.18.27.113:3000
 Checksum     # Nodes   # Alive   # Suspect   # Faulty   Sample Host
 3473867175   5         5         0           0          172.18.27.113:3000
$ ringpop-admin leave 172.18.27.113:3000
$ ./partitions.js --ring 172.18.27.113:3000
 Checksum    # Nodes   # Alive   # Suspect   # Faulty   Sample Host
 436685835   5         4         0           0          172.18.27.113:3000
$ ringpop-admin join 172.18.27.113:3000
$ ./partitions.js --ring 172.18.27.113:3000
 Checksum     # Nodes   # Alive   # Suspect   # Faulty   Sample Host
 3473867175   5         5         0           0          172.18.27.113:3000
```

**Comment by dansimau** [comment]
Code LGTM.

**Comment by severb** [comment]
LGT:moneybag:

**Comment by thanodnl** [comment]
Turns out that the bug is in `ringpop-admin`, luckily the integration tests snitched on this mistake. Closing this PR.

**Pull request closed without merging**
